# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Material:
  fields:
    list: title, original_title
    form: title, original_title, info
  order_by: 
  relationships: 
  filters: 
  search: title
  application: sup

